INSERT INTO `lugars` (`pais`, `provincia`, `ciudad`) VALUES 
('ARGENTINA', 'MISIONES', 'PUERTO IGUAZU'),
('ARGENTINA', 'MISIONES', 'POSADAS'),
('ARGENTINA', 'CORDOBA', 'CORDOBA'),
('ARGENTINA', 'BUENOS AIRES', 'AEROPARQUE'),
('ARGENTINA', 'BUENOS AIRES', 'EZEIZA'),
('ARGENTINA', 'SALTA', 'SALTA'),
('ARGENTINA', 'CHUBUT', 'PUERTO MADRYN'),
('ARGENTINA', 'TIERRA DEL FUEGO', 'USHUAIA'),
('ARGENTINA', 'MENDOZA', 'MENDOZA'),
('ARGENTINA', 'NEUQUEN', 'NEUQUEN');